apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.chartName }}
  namespace: {{ .Values.namespace }}
spec:
  ports:
  - name: http
    port: 80
    targetPort: 8080
  selector:
    app: {{ .Values.chartName }}