kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: dynamic-stage-{{ .Values.name }}
  namespace: dynamic-stages
  argocd.argoproj.io/sync-wave: "-1"
spec:
  triggers:
    - type: "ConfigChange"
  source: 
    git:
      uri: "https://github.com/chtime/var-echo"
      ref: {{ .Values.revision }}
  strategy:
    type: Docker
  output:
    to:
      kind: DockerImage
      name: {{ printf "default-route-openshift-image-registry.apps-crc.testing/myproject/myimage:var-echo:%s" .Values.revision }}