kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: {{ .Values.chartName }}
  namespace: {{ .Values.namespace }}
spec:
  triggers:
    - type: "ConfigChange"
    - type: "GitHub"
      github:
        secretReference:
          name: "mysecret"
  source:
    git:
      uri: "https://github.com/chtime/var-echo"
      ref: {{ .Values.revision }}
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: {{ printf "var-echo:%s" .Values.revision }}
