kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: {{ .Values.chartName }}
  namespace: {{ .Values.namespace }}
spec:
  triggers:
    - type: "ConfigChange"
  source:
    git:
      uri: "https://github.com/chtime/var-echo"
      ref: {{ .Values.revision }}
  strategy:
    type: Docker
  output:
    to:
      kind: ImageStreamTag
      name: "var-echo:latest"
