apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.chartName }}
  namespace: {{ .Values.name_space }}
spec:
  replicas: 3
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: {{ .Values.chartName }}
  template:
    metadata:
      labels:
        app: {{ .Values.chartName }}
    spec:
      containers:
      - name: {{ .Values.chartName }}
        image: {{ printf "default-route-openshift-image-registry.apps-crc.testing/var-echo/var-echo:%s" .Values.revision }}
        ports:
        - containerPort: 8080
        env:
        - name: LE_ENV_VAR
          value: {{ .Values.chartName }}