apiVersion: apps.openshift.io/v1
kind: DeploymentConfig
metadata:
  name: {{ .Values.chartName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 3
  revisionHistoryLimit: 0
  selector:
    app: {{ .Values.chartName }}
  template:
    metadata:
      labels:
        app: {{ .Values.chartName }}
    spec:
      containers:
      - name: {{ .Values.chartName }}
        image: "var-echo:{{ .Values.revision }}"
        ports:
        - containerPort: 8080
        env:
        - name: CHART_NAME
          value: {{ .Values.chartName }}
        - name: STAGE
          value: {{ .Values.stage }}
        - name: NAMESPACE
          value: {{ .Values.namespace }}
        - name: REVISION
          value: {{ .Values.revision }}
  triggers:
  - type: ImageChange
    imageChangeParams:
      automatic: true
      containerNames:
      - {{ .Values.chartName }}
      from:
        kind: ImageStreamTag
        namespace: dev
        name: "var-echo:{{ .Values.revision }}"