apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.chartName }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: 3
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: {{ .Values.chartName }}
  template:
    metadata:
      labels:
        app: {{ .Values.chartName }}
    spec:
      containers:
      - name: {{ .Values.chartName }}
        image: var-echo:latest
        ports:
        - containerPort: 8080
        env:
        - name: LE_ENV_VAR
          value: {{ .Values.chartName }}