
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ .Values.chartName }}
  namespace: {{ .Values.namespace }}
spec:
  host: {{ .Values.chartName }}.apps-crc.testing
  port:
    targetPort: http
  tls:
    termination: edge 
  to:
    kind: Service
    name: {{ .Values.chartName }}
    weight: 100
